package com.retailsvc.http.internal;

import com.retailsvc.http.BadRequestException;
import com.retailsvc.http.validate.ValidationError;
import java.util.Map;

/**
 * Carrier for an RFC 7807 problem+json document. Serialized by the registered JSON {@code
 * TypeMapper}; the wire shape and field-order are whatever the configured mapper produces — title
 * is advisory per RFC 7807 since {@code type} is always {@code about:blank}.
 *
 * @param type URI reference that identifies the problem type. This library always emits {@code
 *     about:blank}, which per RFC 7807 means {@code title} carries the advisory description of the
 *     problem.
 * @param title short, human-readable summary of the problem type (e.g. {@code "Bad Request"}).
 *     Advisory only when {@code type} is {@code about:blank}, but still surfaced to clients.
 * @param status HTTP status code generated by the origin server for this occurrence of the problem;
 *     mirrors the status written on the wire.
 * @param detail human-readable explanation specific to this occurrence of the problem (e.g. the
 *     concrete validation message for the offending request).
 * @param pointer Hii Retail extension to RFC 7807: a JSON Pointer ({@code RFC 6901}) into the
 *     request body identifying the offending property. {@code null} when no pointer applies (e.g.
 *     header / query / generic errors).
 * @param keyword Hii Retail extension to RFC 7807: the JSON Schema (or OpenAPI) validation keyword
 *     that failed, such as {@code "required"}, {@code "type"} or {@code "pattern"}. {@code null}
 *     when the error did not originate from schema validation.
 */
public record ProblemDetail(
    String type, String title, int status, String detail, String pointer, String keyword) {

  private static final String DEFAULT_TYPE = "about:blank";

  /**
   * Builds a {@code ProblemDetail} for a schema/parameter validation failure. Uses {@code
   * about:blank} as the type, {@code "Bad Request"} as the title, status {@code 400}, and copies
   * the message, JSON Pointer and failing keyword from the {@link ValidationError}.
   *
   * @param e the validation error produced by the request validator
   * @return a 400 problem document describing the validation failure
   */
  public static ProblemDetail forValidation(ValidationError e) {
    return new ProblemDetail(
        DEFAULT_TYPE, "Bad Request", 400, e.message(), e.pointer(), e.keyword());
  }

  /**
   * Builds a {@code ProblemDetail} from a {@link BadRequestException} thrown by application code.
   * The status is taken from the exception, the title is resolved from a standard HTTP reason
   * phrase table (falling back to {@code "Bad Request"}), and the optional pointer/keyword are
   * propagated as Hii Retail extensions when present.
   *
   * @param e the bad-request exception raised by the handler chain
   * @return a problem document mirroring the exception's status, message and optional metadata
   */
  public static ProblemDetail forBadRequest(BadRequestException e) {
    return new ProblemDetail(
        DEFAULT_TYPE,
        titleFor(e.status()),
        e.status(),
        e.getMessage(),
        e.pointer().orElse(null),
        e.keyword().orElse(null));
  }

  private static final Map<Integer, String> TITLES =
      Map.of(
          400, "Bad Request",
          401, "Unauthorized",
          403, "Forbidden",
          404, "Not Found",
          405, "Method Not Allowed",
          409, "Conflict",
          410, "Gone",
          412, "Precondition Failed",
          415, "Unsupported Media Type",
          422, "Unprocessable Content");

  private static String titleFor(int status) {
    return TITLES.getOrDefault(status, "Bad Request");
  }
}
