name: Commit
on: push

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - &setup-java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version-file: .java-version
          cache: 'maven'

      - name: Run tests
        uses: extenda/actions/maven@v0
        with:
          args: verify
          service-account-key: ${{ secrets.SECRET_AUTH }}

      - name: Scan with SonarCloud
        uses: extenda/actions/sonar-scanner@v0
        with:
          sonar-host: https://sonarcloud.io
          sonar-scanner: maven
          main-branch: master
          service-account-key: ${{ secrets.SECRET_AUTH }}

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      id-token: write
    steps:
      - *checkout
      - *setup-java

      - name: Create release
        uses: extenda/actions/conventional-release@v0
        id: release
        with:
          name: ''
          tag-prefix: 'v'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build release
        uses: extenda/actions/maven@v0
        with:
          args: deploy -DskipTests
          version: ${{ steps.release.outputs.version }}
          service-account-key: ${{ secrets.SECRET_AUTH }}
